# Generated by Django 3.2.6 on 2021-10-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_season', models.CharField(max_length=200)),
                ('camp_latest', models.BooleanField(default=True)),
                ('camp_days', models.SmallIntegerField()),
                ('camp_nights', models.SmallIntegerField()),
                ('camp_altitude', models.IntegerField()),
                ('camp_difficulty', models.CharField(choices=[('easy', 'EASY'), ('medium', 'MEDIUM'), ('hard', 'HARD')], default=('easy', 'EASY'), max_length=20)),
                ('camp_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('camp_note', models.CharField(max_length=250)),
                ('camp_brochure', models.FileField(upload_to='img/documents')),
                ('packages', models.TextField(help_text='Enter colon(;) seperated packages, E.g Goa to Goa, 12500;Jammu to Jammu, 15000')),
                ('camp_dates', models.TextField(help_text='Enter colon(;) seperated dates, E.g AUG 12 2021; JUL 19 2021')),
                ('camp_about', models.TextField()),
                ('camp_schedules', models.TextField(help_text='Enter colon(;) seperated schedules for each day, E.g Departure form Ahmedabad 11:00 am; Arrival at Ahmedabad with Adventures memories')),
                ('places_to_visit', models.TextField(help_text='Enter colon(;) seperated places')),
                ('activities', models.TextField(help_text='Enter colon(;) seperated activities')),
                ('inclusions', models.TextField(help_text='Enter colon(;) seperated inclusions')),
                ('exclusions', models.TextField(help_text='Enter colon(;) seperated exclusions')),
                ('carried_things', models.TextField(help_text='Enter colon(;) seperated things')),
                ('guidelines', models.TextField(help_text='Enter colon(;) seperated guidelines')),
                ('instructions', models.TextField(help_text='Enter colon(;) seperated instructions')),
                ('suggestions', models.TextField(blank=True, help_text='Enter colon(;) seperated suggestions')),
            ],
        ),
    ]
