# Generated by Django 3.2.6 on 2021-10-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campmodel',
            name='camp_dates',
            field=models.TextField(help_text='Enter colon(;) seperated dates, E.g MAR 6 2021; MAY 22 2021'),
        ),
        migrations.AlterField(
            model_name='campmodel',
            name='camp_schedules',
            field=models.TextField(help_text='Enter colon(;) seperated schedules for each day, E.g Departure form Vadodara 1:00 am; Arrival at Vadodara'),
        ),
        migrations.AlterField(
            model_name='campmodel',
            name='packages',
            field=models.TextField(help_text='Enter colon(;) seperated packages, E.g Kedarnath To Kedarnath, 15000;Jammu to Jammu, 15000'),
        ),
    ]
