# Generated by Django 3.2.6 on 2021-10-14 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Camps', '0002_auto_20211014_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='campmodel',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campmodel',
            name='image',
            field=models.ImageField(default='user-default.png', upload_to='img/campImages'),
        ),
        migrations.AddField(
            model_name='campmodel',
            name='title',
            field=models.CharField(default='Default Camp', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
