# Generated by Django 3.2.6 on 2021-10-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camps', '0003_auto_20211014_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campmodel',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
