# Generated by Django 3.2.6 on 2021-10-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camps', '0008_aboutmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='about_latest',
            field=models.BooleanField(default=True),
        ),
    ]
