# Generated by Django 3.2.6 on 2021-10-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camps', '0012_instalinkmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('package', models.CharField(default='', max_length=200)),
                ('date', models.CharField(default='', max_length=100)),
                ('rate', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=100)),
                ('mobile', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=300)),
                ('id_proof', models.ImageField(upload_to='images/formdata')),
                ('photo', models.ImageField(upload_to='images/formdata')),
                ('bdate', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=10)),
                ('blood_group', models.CharField(default='', max_length=5)),
                ('weight', models.IntegerField(default='')),
                ('occupation', models.CharField(default='', max_length=100)),
                ('organization', models.CharField(default='', max_length=300)),
                ('guardian_name', models.CharField(default='', max_length=200)),
                ('guardian_email', models.CharField(default='', max_length=200)),
                ('guardian_mobile', models.CharField(default='', max_length=20)),
                ('participated_where', models.CharField(default='', max_length=300)),
                ('disease_phobia', models.CharField(default='', max_length=300)),
                ('reference', models.CharField(default='', max_length=50)),
                ('online_name', models.CharField(blank=True, default='', max_length=300)),
                ('online_email', models.CharField(blank=True, default='', max_length=200)),
                ('online_mobile', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
    ]
