# Generated by Django 3.2.6 on 2021-10-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camps', '0013_conformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='youTubeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.CharField(max_length=5000)),
            ],
        ),
    ]
